AllCops:
  TargetRubyVersion: 2.7
  Exclude:
    - bin/*
    - db/*

Metrics/LineLength:
  Max: 140

Metrics/CyclomaticComplexity:
  Max: 10

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb
